### ISSUE TITLE
Sendmail is broken

### ISSUE THREAD

**Issue by HON95** [CasualGaming/studlan#355]
While working perfectly in my test environment, it breaks on certain prod situations.

When sending to 200 ticket owners:

```
Internal Server Error: /sendmail/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./apps/sendmail/views.py", line 26, in sendmail_send
    form = handle_submitted_form(request, old_form, template_context)
  File "./apps/sendmail/views.py", line 113, in handle_submitted_form
    message.recipient_tickets = tickets
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 536, in __set__
    manager = self.__get__(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 513, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 830, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by HON95** [comment]
Fixed?
